### PR TITLE
[v2.1] Support activerecord 8.0

### PR DESCRIPTION
**Pull request by tnir**
Support Active Record (activerecord gem) 8.0.

## Notes

- beta1 was ready last month: https://rubyonrails.org/2024/9/27/rails-8-beta1-no-paas-required
- rc1 is already out: https://rubygems.org/gems/rails/versions/8.0.0.rc1?locale=en

### CODE REVIEW

**Comment by winebarrel** [comment]
I created a branch for v2.1, so could you use that as the base of the branch?
https://github.com/ridgepole/ridgepole/tree/2.1

**Comment by tnir** [comment]
@winebarrel Make sense. Changed the target branch to `2.1` branch.

**Comment by tnir** [comment]
@winebarrel I guess you should have created v2.2 branch instead of v2.1, shouldn't you? v2.1 branch should be preserved for Rails 7.2?

**Comment by winebarrel** [comment]
@tnir Sorry for the late reply.
I agree with your idea and have changed the branch name from 2.1 to 3.0.

**Review by winebarrel — APPROVED** [review]

**Comment by tnir** [comment]
Thanks! 🎉

**Comment by winebarrel** [comment]
v3.0.0 has been released

**Pull request merged**
